#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("reto8.Resource", IsApplication=true)]

namespace reto8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int tiendav = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int LinearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int btnAddProducto = 2131165200;
			
			// aapt resource value: 0x7f07000f
			public const int btnEliminar = 2131165199;
			
			// aapt resource value: 0x7f070015
			public const int btnIniciarSesion = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int button1 = 2131165203;
			
			// aapt resource value: 0x7f070003
			public const int buttonAddToDo = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int buttonLoginUser = 2131165188;
			
			// aapt resource value: 0x7f070016
			public const int checkProductoItem = 2131165206;
			
			// aapt resource value: 0x7f070018
			public const int checkToDoItem = 2131165208;
			
			// aapt resource value: 0x7f070007
			public const int editText1 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int editText2 = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int editText3 = 2131165195;
			
			// aapt resource value: 0x7f07000d
			public const int editText4 = 2131165197;
			
			// aapt resource value: 0x7f070014
			public const int imageView1 = 2131165204;
			
			// aapt resource value: 0x7f07000e
			public const int linearLayout1 = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int listViewToDo = 2131165189;
			
			// aapt resource value: 0x7f070019
			public const int menu_refresh = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int precioProductoItem = 2131165207;
			
			// aapt resource value: 0x7f070002
			public const int textNewToDo = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int textView1 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int textView2 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textView3 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int textView4 = 2131165196;
			
			// aapt resource value: 0x7f070001
			public const int textViewTitle = 2131165185;
			
			// aapt resource value: 0x7f070012
			public const int txtDescripcion = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int txtNombre = 2131165201;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_To_Do = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Agregar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ListProducto = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Login = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Productos = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Row_List_Producto = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Row_List_To_Do = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_main = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int add_button_text = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int add_textbox_hint = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int checkbox_text = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int login_button_text = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int menu_refresh = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int mobile_services = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int AppBaseTheme = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int AppTheme = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
